language: c++

services:
  - docker

env:
  - BADGE=linux

before_install:
  - docker pull notcompsky/tagem-compile-1
  - git clone https://github.com/NotCompsky/libcompsky && mkdir libcompsky/build && cd libcompsky/build && cmake .. -DCMAKE_BUILD_TYPE=Release && make install

script:
  - git clone https://github.com/NotCompsky/tagem && mkdir tagem/build && chmod +x tagem/wangle-server/scripts/* && cd tagem/build && cmake ../wangle-server -DCURL_INCLUDE_DIR=/usr/local/include -DCURL_LIBRARY=/usr/lib/x86_64-linux-gnu/libcurl.so -DCMAKE_BUILD_TYPE=Release -Dwangle_DIR=/bob-the-builder/wangle/ -Dfolly_DIR=/bob-the-builder/folly/ -Dfizz_DIR=/bob-the-builder/fizz/ && make server
