#!/usr/bin/env bash


url="$2"
dst="$1"

if [ -f "$dst" ]; then
	exit 0
fi

echo 'R"=========(' > "$dst"
curl "$url" >> "$dst"
echo ')========="' >> "$dst"

# | sed -E -e "s/\"/\\\"/g" -e "s/^[\\s]([^\\s].*$)/\"\\1\"/g" \
