#!/bin/sh

build_img(){
	fp_orig="$1"
	fp="$2"
	
	fp="$(echo "$fp_orig" | sed -E 's/[.](png|ico)$/.txt/g')"
	if [ "$fp" = "$fp_orig" ]; then
		echo "fp == fp_orig == $fp" >&2
		exit 1
	fi
	if [ -f "$fp" ]; then
		# Already exists
		exit 0
	fi
	printf 'R"=====(' >  "$fp"
	cat "$fp_orig"    >> "$fp"
	printf ')====="'  >> "$fp"
}

build_img "$@"
