version: 2
jobs:
  build:
    docker:
      - image: notcompsky/tagem-compile-1

    steps:
      - checkout


      - run:
          name: apt install extras
          command: apt install -y --no-install-recommends libffmpegthumbnailer-dev
      - run:
          name: Get CImg header without installing dependencies, because the dependencies are broken
          command: curl -s https://raw.githubusercontent.com/dtschump/CImg/master/CImg.h > /usr/include/CImg.h


      - run:
          name: libcompsky - Download
          command: 'git clone --depth 1 https://github.com/NotCompsky/libcompsky'
      - run:
          name: libcompsky - Build
          command: 'mkdir libcompsky/build  &&  cd libcompsky/build  &&  cmake ..  &&  make  &&  make install  &&  cd ../..'

      - run:
          name: tagem - Download
          command: 'git clone --depth 1 --recurse-submodules https://github.com/NotCompsky/tagem'
      - run:
          name: tagem - Build
          command: 'mkdir tagem/build  &&  chmod +x tagem/wangle-server/scripts/*  &&  cd tagem/build  &&  cmake ../wangle-server -Dproxygen_root_DIR=../../proxygen -DCURL_INCLUDE_DIR=/usr/local/include -DCURL_LIBRARY=/usr/lib/x86_64-linux-gnu/libcurl.so -DCMAKE_BUILD_TYPE=Release -Dwangle_DIR=/bob-the-builder/wangle/ -Dfolly_DIR=/bob-the-builder/folly/ -Dfizz_DIR=/bob-the-builder/fizz/  &&  make server'
      - store_artifacts:
          path: /tagem/build/server
          destination: server
