version: 2
general:
  artifacts:
    - "packages"
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Update Apt Cache
          command: 'apt update'

      - run:
          name: Enable SUDO # See: https://discuss.circleci.com/t/sudo-command-not-found/14208/4
          command: apt-get install -y sudo
      - run:
          name: Use BASH instead of DASH # See https://ubuntuforums.org/showthread.php?t=1932504
          command: 'ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh'

      - run:
          name: Install Dependencies 
          command: 'apt install -y git curl wget g++ cmake'

      - run:
          name: libcompsky - Download
          command: 'git clone https://github.com/NotCompsky/libcompsky'
      - run:
          name: libcompsky - Install SQL Client Dev
          command: 'apt install -y mariadb-client default-libmysqlclient-dev' # qt5-default libqt5widgets5 libqt5charts5 libqt5charts5-dev
      - run:
          name: libcompsky - Generate build files
          command: 'mkdir libcompsky/build  &&  cd libcompsky/build  &&  cmake ..  &&  make  &&  make install  &&  cd ../..'

      - run:
          name: proxygen - Download
          command: 'git clone https://github.com/facebook/proxygen'
      - run:
          name: proxygen - Build
          command: 'cd proxygen/proxygen  &&  sed -i "s/setup_wangle$/setup_wangle; exit 0/g" build.sh  &&  ./build.sh --no-tests  &&  cd ../..'

      - run:
          name: tagem - Download
          command: 'git clone https://github.com/NotCompsky/tagem'
      - run:
          name: tagem - Build
          command: 'mkdir tagem/build  &&  cd tagem/build  &&  cmake .. -Dproxygen_root_DIR=../../proxygen -DMAX_CACHE_AGE=0 -DCMAKE_BUILD_TYPE=Release  &&  make server'
