default: man/mytag.1 man/mytagtxt.1 man/mytagvid.1

man/mytag.1:
	pandoc -s -t man docs/mytag.1.md    -o man/mytag.1

man/mytagtxt.1:
	pandoc -s -t man docs/mytagtxt.1.md -o man/mytagtxt.1

man/mytagvid.1:
	pandoc -s -t man docs/mytagvid.1.md -o man/mytagvid.1
