#!/usr/bin/env bash


outpath="$1"


cmd=(ffmpeg)
declare -i i=2
declare -i n=${#@} # Number of arguments

while [ $i -lt $n ]; do
	era_start="${!i}" # Get ith positional argument
	((++i))
	era_end="${!i}"
	((++i))
	url="${!i}"
	((++i))
	
	echo "Extracting era from: ${url}" >&2
	
	urls=($(youtube-dl -g "$url"))
	cmd+=(-ss "$era_start" -to "$era_end" -i "${urls[0]}")
	if [ ${#urls[@]} -eq 2 ]; then
		cmd+=(-ss "$era_start" -to "$era_end" -i "${urls[1]}")
	fi
done <<< "$@"


echo "${cmd[@]}" >&2

"${cmd[@]}" -vcodec copy -acodec copy "$outpath"
