#!/usr/bin/env bash


outpath="$1"
cmds=(ffmpeg)
while read -r era_start era_end url; do
	urls=($(youtube-dl -g "$url"))
	cmd+=(-ss "$era_start" -to "$era_end" -i "${urls[0]}")
	if [ ${#urls[@]} -eq 2 ]; then
		cmd+=(-ss "$era_start" -to "$era_end" -i "${urls[1]}")
	fi
done
"${cmds[@]}" -vcodec copy -acodec copy "$outpath"
