#!/bin/bash

# An example shell script to demonstrate how one can capture characteristics of each file and apply them to a (pre-existing) table.


HOST=$(cat "$TAGEM_MYSQL_CFG" | grep ^HOST: | sed 's/^HOST: //g')
USER=$(cat "$TAGEM_MYSQL_CFG" | grep ^USER: | sed 's/^USER: //g')
PWRD=$(cat "$TAGEM_MYSQL_CFG" | grep ^PWRD: | sed 's/^PWRD: //g')
DBNM=$(cat "$TAGEM_MYSQL_CFG" | grep ^DBNM: | sed 's/^DBNM: //g')



declare -i i=0
cmd="" # Dummy that will lead to an error
while read line; do
	IFS=$'\t' read id fp <<< "$line"
	sz=$(stat -c "%s" "$fp" 2>/dev/null)
	if [ $? = 0 ]; then
		if [ $((i % 1000)) = 0 ]; then
			mysql --user="$USER" --password="$PWRD" -e "$cmd(0,0)" "$DBNM"
			cmd="INSERT IGNORE INTO file2size (file, x) VALUES"
			i=0
		fi
		i+=1
		cmd="$cmd($id,$sz),"
	fi
done < <(mysql --user="$USER" --password="$PWRD" -e "
SELECT f.id, f.name
FROM file f
LEFT JOIN file2size f2s ON f2s.file=f.id
WHERE f2s.x IS NULL
" "$DBNM")

mysql --user="$USER" --password="$PWRD" -e "$cmd(0,0)" "$DBNM"
