#!/usr/bin/env bash


get_auth(){
	echo "$(echo "$1" | grep "^$2: " | sed "s_^$2: __g")"
}


auth="$(cat "$TAGEM_MYSQL_CFG")"
host="$(get_auth "$auth" HOST)"
path="$(get_auth "$auth" PATH)"
user="$(get_auth "$auth" USER)"
pwrd="$(get_auth "$auth" PWRD)"
port="$(get_auth "$auth" PORT)"
tagem_auth=(--host "$host" --user "$user" --password="$pwrd" --socket="$path")
if [ "$port" = "" ]; then
	dummy=1
else
	tagem_auth+=(--port "$port")
fi
