#!/usr/bin/env bash


if [ "$USER_AGENT" = "" ]; then
	USER_AGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36'
fi
if [ "$DIR" = "" ]; then
	DIR="$(dirname "$(realpath "$0")")/remote-dir-viewers/"
fi

page="$1"
url="$2"

if [ "$(echo "$url" | grep -E '^pinterest ')" ]; then
	# pinterest [QRY]
	if [ "$PINTEREST_COOKIES" = "" ]; then
		echo "Error: No pinterest cookies were supplied!" >&2
	fi
	"$DIR/pinterest.com" "$page" "$url"
else
	echo "No dir viewer for URL: $url" >&2
	exit
fi
